### ISSUE TITLE
fails react

### ISSUE THREAD

**Issue by spearmootz** [jabuco/parcel-plugin-obfuscate#3]
because obfuscation happens before the code is transpiled to JS, the process fails.

if it was at the very end then it would work for pretty much anything.

**Comment by peanutbother** [comment]
might have to do with issue  #1 and #2 
https://github.com/jabuco/parcel-plugin-obfuscate/issues/1#issuecomment-788976185

**Comment by peanutbother** [comment]
If this issue still persisted in v**2.1.1**, I will reopen it.
I tested with react + react-dom which worked fine.
