### ISSUE TITLE
After we install it, can you add how we generate the file using `yarn build`?

### ISSUE THREAD

**Issue by nonopolarity** [jabuco/parcel-plugin-obfuscate#4]
Can the doc add after we do

```
yarn add -D parcel-plugin-obfuscate
```
how do we do `yarn build` so that the code is obfuscated?  Right now it is the same as before..

**Comment by peanutbother** [comment]
right now `parcel-plugin-obfuscate` only obfuscates the code if minify  (production) is enabled.

you can either require parcel, register plugin and compile your code with it or the easier way:

set `NODE_ENV=production` to compile in production code which enables obfuscation too.


I will update the readme to reflect that.
